import type { BodyDef } from "@/components/starfield/system";

type Seed = {
  id: string;
  name: string;
  x: number;
  y?: number;
  z: number;
  color: [number, number, number];
  span: number;
  form: NonNullable<BodyDef["form"]>;
  group: string;
  place: string;
  year: string;
  moons: string;
  blurb: string;
  goal?: boolean;
};

function place(chapter: string, seed: Seed): BodyDef {
  return {
    id: seed.id,
    name: seed.name,
    au: 0,
    diameterKm: 1,
    color: seed.color,
    angle: 0,
    periodDays: 0,
    moons: seed.moons,
    year: seed.year,
    blurb: seed.blurb,
    goal: seed.goal !== false,
    nav: true,
    group: seed.group,
    place: seed.place,
    at: { x: seed.x, y: seed.y ?? 0, z: seed.z },
    span: seed.span,
    form: seed.form,
    chapter,
  };
}

const star = (seed: Seed) => place("stars", seed);
const galaxy = (seed: Seed) => place("galaxy", seed);
const local = (seed: Seed) => place("local", seed);
const web = (seed: Seed) => place("web", seed);

/** Real places beyond the Sun, each chapter on its own map. */
export const JOURNEY: BodyDef[] = [
  star({
    id: "sol",
    name: "Sol",
    x: 0,
    z: 0,
    color: [0.98, 0.84, 0.5],
    span: 18,
    form: "star",
    group: "Home",
    place: "The Sun, behind you",
    year: "G2 star",
    moons: "Home star",
    blurb: "The star you just left, seen from outside its system.",
    goal: false,
  }),
  star({
    id: "proxima",
    name: "Proxima Centauri",
    x: 48,
    z: 320,
    color: [0.95, 0.34, 0.22],
    span: 16,
    form: "star",
    group: "Home",
    place: "4.2 light-years",
    year: "Red dwarf",
    moons: "Nearest",
    blurb: "The nearest star to the Sun. A cool red dwarf with a planet in its temperate zone.",
  }),
  star({
    id: "alpha",
    name: "Alpha Centauri",
    x: 280,
    y: 30,
    z: 340,
    color: [1, 0.94, 0.78],
    span: 30,
    form: "star",
    group: "Home",
    place: "4.4 light-years",
    year: "Sunlike pair",
    moons: "Binary",
    blurb: "Two sunlike stars swinging around each other. Proxima is their distant third.",
  }),
  star({
    id: "barnard",
    name: "Barnard's Star",
    x: -300,
    y: -20,
    z: 480,
    color: [0.9, 0.28, 0.18],
    span: 14,
    form: "star",
    group: "Home",
    place: "6.0 light-years",
    year: "Red dwarf",
    moons: "Fastest",
    blurb: "A dim red dwarf with the fastest motion across the sky of any star.",
  }),
  star({
    id: "sirius",
    name: "Sirius",
    x: 950,
    z: 320,
    color: [0.88, 0.94, 1],
    span: 42,
    form: "star",
    group: "Bright",
    place: "8.6 light-years",
    year: "White star",
    moons: "Brightest",
    blurb: "The brightest star in the night sky. A white dwarf, the Pup, orbits it.",
  }),
  star({
    id: "procyon",
    name: "Procyon",
    x: -1080,
    y: 80,
    z: 700,
    color: [1, 0.93, 0.74],
    span: 30,
    form: "star",
    group: "Bright",
    place: "11.5 light-years",
    year: "White-yellow",
    moons: "With a dwarf",
    blurb: "One of the dog stars. A white dwarf circles the bright one.",
  }),
  star({
    id: "altair",
    name: "Altair",
    x: 1520,
    y: -40,
    z: -480,
    color: [0.92, 0.95, 1],
    span: 32,
    form: "star",
    group: "Bright",
    place: "16.7 light-years",
    year: "White star",
    moons: "Fast spin",
    blurb: "A white star spinning so fast it is flattened at the poles.",
  }),
  star({
    id: "vega",
    name: "Vega",
    x: -1680,
    y: 140,
    z: 1100,
    color: [0.72, 0.84, 1],
    span: 38,
    form: "star",
    group: "Bright",
    place: "25 light-years",
    year: "Blue-white",
    moons: "Pole star once",
    blurb: "A blue-white star that was the pole star around 12,000 BCE, and will be again.",
  }),
  star({
    id: "fomalhaut",
    name: "Fomalhaut",
    x: 820,
    y: -160,
    z: 2200,
    color: [0.95, 0.95, 0.88],
    span: 28,
    form: "star",
    group: "Bright",
    place: "25 light-years",
    year: "White star",
    moons: "Debris ring",
    blurb: "A white star with a bright ring of dust and a disputed planet.",
  }),
  star({
    id: "arcturus",
    name: "Arcturus",
    x: -700,
    y: 90,
    z: 2800,
    color: [1, 0.58, 0.26],
    span: 54,
    form: "star",
    group: "Giants",
    place: "37 light-years",
    year: "Orange giant",
    moons: "Old star",
    blurb: "An orange giant, older than the Sun, and the brightest star of the northern spring.",
  }),
  star({
    id: "betelgeuse",
    name: "Betelgeuse",
    x: 2400,
    y: 180,
    z: 2600,
    color: [1, 0.32, 0.12],
    span: 82,
    form: "star",
    group: "Giants",
    place: "About 550 light-years",
    year: "Red supergiant",
    moons: "Unsteady",
    blurb: "A red supergiant large enough to swallow the inner planets. It will end as a supernova.",
  }),
  star({
    id: "polaris",
    name: "Polaris",
    x: -400,
    y: 420,
    z: 4200,
    color: [1, 0.9, 0.58],
    span: 46,
    form: "star",
    group: "Giants",
    place: "About 450 light-years",
    year: "Yellow supergiant",
    moons: "North star",
    blurb: "The north star of this century. It is a triple, and the bright one pulses.",
  }),
  galaxy({
    id: "orion-arm",
    name: "Orion Arm",
    x: 0,
    z: 420,
    color: [0.62, 0.74, 0.95],
    span: 88,
    form: "cloud",
    group: "Here",
    place: "Our minor arm",
    year: "Stellar spur",
    moons: "The Sun lives here",
    blurb: "A spur between two great arms. The Sun and every near star sit inside it.",
  }),
  galaxy({
    id: "local-bubble",
    name: "Local Bubble",
    x: -780,
    y: 40,
    z: -260,
    color: [0.55, 0.62, 0.78],
    span: 54,
    form: "cloud",
    group: "Here",
    place: "About 300 light-years across",
    year: "Hot cavity",
    moons: "We are inside",
    blurb: "A cavity of thin hot gas. Ancient supernovae cleared it, and the Sun drifts inside.",
  }),
  galaxy({
    id: "pleiades",
    name: "Pleiades",
    x: 1100,
    y: 180,
    z: 700,
    color: [0.78, 0.86, 1],
    span: 50,
    form: "cluster",
    group: "Clusters",
    place: "About 440 light-years",
    year: "Open cluster",
    moons: "Young stars",
    blurb: "A handful of hot young stars still wrapped in the dust they formed from.",
  }),
  galaxy({
    id: "orion-nebula",
    name: "Orion Nebula",
    x: -1300,
    y: -90,
    z: 1500,
    color: [0.95, 0.48, 0.62],
    span: 78,
    form: "cloud",
    group: "Clusters",
    place: "About 1,300 light-years",
    year: "Star nursery",
    moons: "New suns",
    blurb: "The nearest great nursery. New stars are lighting up inside the cloud.",
  }),
  galaxy({
    id: "crab",
    name: "Crab Nebula",
    x: 1600,
    y: 70,
    z: 1900,
    color: [0.95, 0.62, 0.45],
    span: 44,
    form: "cloud",
    group: "Clusters",
    place: "About 6,500 light-years",
    year: "Supernova shell",
    moons: "Seen in 1054",
    blurb: "The wreck of a star that exploded in 1054. A pulsar still spins at the center.",
  }),
  galaxy({
    id: "carina",
    name: "Carina Nebula",
    x: -700,
    z: 2500,
    color: [0.95, 0.55, 0.42],
    span: 74,
    form: "cloud",
    group: "Clusters",
    place: "About 7,500 light-years",
    year: "Star nursery",
    moons: "Massive stars",
    blurb: "A vast nursery in the southern sky, home to some of the heaviest stars in the galaxy.",
  }),
  galaxy({
    id: "omega",
    name: "Omega Centauri",
    x: 980,
    y: -180,
    z: 2700,
    color: [1, 0.84, 0.55],
    span: 52,
    form: "cluster",
    group: "Clusters",
    place: "About 17,000 light-years",
    year: "Globular cluster",
    moons: "Millions of stars",
    blurb: "The largest globular cluster in the galaxy. It may be the core of a dwarf galaxy that was swallowed.",
  }),
  galaxy({
    id: "perseus-arm",
    name: "Perseus Arm",
    x: -1700,
    y: 80,
    z: 3200,
    color: [0.5, 0.64, 0.92],
    span: 72,
    form: "cloud",
    group: "Arms",
    place: "Outward of us",
    year: "Major arm",
    moons: "Star-forming",
    blurb: "One of the two great arms you can see from Earth, outward of the Orion spur.",
  }),
  galaxy({
    id: "core",
    name: "Galactic Core",
    x: 180,
    z: 4500,
    color: [1, 0.7, 0.32],
    span: 128,
    form: "cluster",
    group: "Arms",
    place: "About 26,000 light-years",
    year: "Dense center",
    moons: "Sagittarius A*",
    blurb: "The crowded heart of the Milky Way. A supermassive black hole, Sagittarius A*, sits in the middle. Orbit it. Do not skim it.",
  }),
  galaxy({
    id: "far-disc",
    name: "Far Disc",
    x: -500,
    y: 120,
    z: 5600,
    color: [0.45, 0.52, 0.72],
    span: 96,
    form: "cloud",
    group: "Arms",
    place: "The other side",
    year: "Far stars",
    moons: "Hidden by the core",
    blurb: "The far half of the disc, seen past the core. Dust hides most of it from Earth.",
  }),
  local({
    id: "home-galaxy",
    name: "Milky Way",
    x: 0,
    z: -500,
    color: [0.75, 0.8, 0.95],
    span: 210,
    form: "galaxy",
    group: "Home",
    place: "Behind you",
    year: "Barred spiral",
    moons: "Your galaxy",
    blurb: "Home, seen from outside. The disc, the core, and the arms are one shape from here.",
    goal: false,
  }),
  local({
    id: "lmc",
    name: "Large Magellanic Cloud",
    x: 1100,
    y: -80,
    z: 900,
    color: [0.95, 0.78, 0.62],
    span: 150,
    form: "cloud",
    group: "Companions",
    place: "About 160,000 light-years",
    year: "Irregular galaxy",
    moons: "Satellite",
    blurb: "The largest satellite of the Milky Way, and a galaxy in its own right. This is the first step outside.",
  }),
  local({
    id: "smc",
    name: "Small Magellanic Cloud",
    x: 1900,
    y: 80,
    z: 200,
    color: [0.9, 0.72, 0.7],
    span: 96,
    form: "cloud",
    group: "Companions",
    place: "About 200,000 light-years",
    year: "Irregular galaxy",
    moons: "Satellite",
    blurb: "The smaller Magellanic cloud. A bridge of gas still ties it to the larger one.",
  }),
  local({
    id: "barnard-galaxy",
    name: "Barnard's Galaxy",
    x: -1500,
    y: 40,
    z: 1700,
    color: [0.72, 0.7, 0.85],
    span: 68,
    form: "cloud",
    group: "Companions",
    place: "About 1.6 million light-years",
    year: "Irregular galaxy",
    moons: "NGC 6822",
    blurb: "A small irregular galaxy in the Local Group, far past the Magellanic Clouds.",
  }),
  local({
    id: "triangulum",
    name: "Triangulum",
    x: 500,
    y: 220,
    z: 3400,
    color: [0.7, 0.78, 0.98],
    span: 140,
    form: "galaxy",
    group: "Great",
    place: "About 2.7 million light-years",
    year: "Spiral",
    moons: "Third largest",
    blurb: "The third large galaxy of the Local Group, a clean spiral with a bright inner disc.",
  }),
  local({
    id: "andromeda",
    name: "Andromeda",
    x: -900,
    y: 20,
    z: 4800,
    color: [0.78, 0.82, 1],
    span: 240,
    form: "galaxy",
    group: "Great",
    place: "About 2.5 million light-years",
    year: "Spiral",
    moons: "Largest here",
    blurb: "The nearest great spiral. It is coming toward the Milky Way, and the two will meet in a few billion years.",
  }),
  web({
    id: "virgo",
    name: "Virgo Cluster",
    x: 0,
    z: 520,
    color: [0.95, 0.86, 0.62],
    span: 160,
    form: "cluster",
    group: "Near",
    place: "About 54 million light-years",
    year: "Galaxy cluster",
    moons: "About 2,000",
    blurb: "The nearest major cluster. Thousands of galaxies, and the heart of our local supercluster.",
  }),
  web({
    id: "fornax",
    name: "Fornax Cluster",
    x: 1700,
    y: -40,
    z: 1100,
    color: [0.9, 0.78, 0.58],
    span: 110,
    form: "cluster",
    group: "Near",
    place: "About 62 million light-years",
    year: "Galaxy cluster",
    moons: "Second nearby",
    blurb: "The second rich cluster within reach, in the southern sky.",
  }),
  web({
    id: "attractor",
    name: "Great Attractor",
    x: -1900,
    z: 2300,
    color: [0.72, 0.4, 0.38],
    span: 200,
    form: "cloud",
    group: "Far",
    place: "About 200 million light-years",
    year: "Mass we cannot see",
    moons: "Behind the disc",
    blurb: "A pull on our whole neighborhood. The Milky Way’s dust hides most of what is doing the pulling.",
  }),
  web({
    id: "perseus-cluster",
    name: "Perseus Cluster",
    x: 700,
    y: -100,
    z: 3600,
    color: [0.85, 0.7, 0.55],
    span: 130,
    form: "cluster",
    group: "Far",
    place: "About 240 million light-years",
    year: "Galaxy cluster",
    moons: "X-ray bright",
    blurb: "A massive cluster with a bright galaxy at its center and a pool of hot gas.",
  }),
  web({
    id: "coma",
    name: "Coma Cluster",
    x: -600,
    y: 140,
    z: 4500,
    color: [0.95, 0.9, 0.7],
    span: 150,
    form: "cluster",
    group: "Far",
    place: "About 320 million light-years",
    year: "Galaxy cluster",
    moons: "Thousands",
    blurb: "A dense cluster of thousands of galaxies, mostly old ellipticals, in the hair of Berenice.",
  }),
  web({
    id: "shapley",
    name: "Shapley Supercluster",
    x: 300,
    y: 40,
    z: 5800,
    color: [1, 0.8, 0.5],
    span: 190,
    form: "cluster",
    group: "Far",
    place: "About 650 million light-years",
    year: "Supercluster",
    moons: "The great concentration",
    blurb: "The densest concentration of galaxies in the nearby universe. Farther than this, the chart ends.",
  }),
];
